class CK2CharacterList < Array

  @@character_column={
		:id => nil,
		:dynasty_id => nil,
		:dynasty_name => nil,
		:dynasty_name_jp => nil,
		:name_count => nil,
		:name1 => nil,
		:name1_jp => nil,
		:name2_date => nil,
		:name2 => nil,
		:name2_jp => nil,
		:name3_date => nil,
		:name3 => nil,
		:name3_jp => nil,
		:name4_date => nil,
		:name4 => nil,
		:name4_jp => nil,
		:name5_date => nil,
		:name5 => nil,
		:name5_jp => nil,
		:name6_date => nil,
		:name6 => nil,
		:name6_jp => nil,
		:father_count => nil,
    :father1_date => nil,
    :father1_id => nil,
		:father1_name => nil,
    :father1_name_ja => nil,
    :father2_date => nil,
    :father2_id => nil,
		:father2_name => nil,
    :father2_name_ja => nil,
    :father3_date => nil,
    :father3_id => nil,
		:father3_name => nil,
		:father3_name_ja => nil,
		:real_father_id => nil,
		:real_father_name => nil,
		:real_father_name_jp => nil,
		:mother_id => nil,
		:mother_name => nil,
		:mother_name_jp => nil,
		:female => nil,
		:martial => nil,
		:diplomacy => nil,
		:intrigue => nil,
		:stewardship => nil,
		:learning => nil,
		:religion => nil,
		:culture => nil,
		:traits => nil,	
		:add_claims => nil,
		:birth => nil,
		:death => nil,
		:random_traits => nil,
		:health => nil,
		:fertility => nil,
		:occluded => nil,
		:dna => nil,
		:properties => nil,
		:file => nil,
		:dates => nil
  }
  
  def get_character_column
    @@character_column
  end
end